# Generated by Django 5.2.4 on 2025-07-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={},
        ),
        migrations.AlterModelManagers(
            name="users",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="users",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="users",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="users",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="users",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="users",
            name="last_name",
        ),
        migrations.AddField(
            model_name="users",
            name="Role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User")], default="user"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(unique=True),
        ),
    ]
