# Generated by Django 5.2.4 on 2025-07-22 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_users_is_staff_alter_users_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
