# Generated by Django 5.2.4 on 2025-08-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_users_date_joined_users_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="Role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User"), ("teacher", "Teacher")],
                default="user",
            ),
        ),
    ]
