# Generated by Django 5.2.4 on 2025-08-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_users_username_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="Role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User"), ("teacher", "Teacher")],
                default="user",
                max_length=20,
            ),
        ),
    ]
