# Generated by Django 5.2.4 on 2025-08-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("company", models.CharField(blank=True)),
                ("stock", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("decor", "Decorative Items"),
                            ("religious", "Religious Artifacts"),
                            ("handicraft", "Handicrafts"),
                            ("musical", "Musical Instruments"),
                            ("antique", "Antiques & Collectibles"),
                            ("others", "Others"),
                        ]
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
