# Generated by Django 5.2.4 on 2025-08-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("decor", "Decorative Items"),
                    ("religious", "Religious Artifacts"),
                    ("handicraft", "Handicrafts"),
                    ("musical", "Musical Instruments"),
                    ("antique", "Antiques & Collectibles"),
                    ("others", "Others"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="company",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
